entrypoint: bundle exec rackup -p $PORT
env: flex
runtime: ruby
health_check:
  enable_health_check: False
env_variables:
  SECRET_KEY_BASE: 'mysecretkey'
  PUBLISHABLE_KEY: "pk_test_MvCgaVzdEUl9s39qujuCKHkl"
  SECRET_KEY: "sk_test_bsTQg6cwUhdiDq0p9b1LkaLl"
